#2 Commit para fondo infinito
Nahum-png/SpongeBob-UnderwaterAdventures pull request #5
Opened 2020-12-03 14:49 UTC by Nahum-png

2020-12-03 15:06 UTC, iuresti requested changes

2020-12-03 15:06 UTC, iuresti commented on Game.java
> +        private Background img, img2;
Usen nombres descriptivos

2020-12-03 15:06 UTC, iuresti commented on Records.java
> +            String nameRecords ="C:\\Users\\Sacrificio Music\\Documents\\GRee\\Proyectofinal\\SpongeBobRace";
No usen rutas en hard-code .. esto solo va a funcionar en la máquina donde lo hicieron

2020-12-03 15:06 UTC, iuresti commented on Records.java
> +        try
Usen try con recursos:
https://picodotdev.github.io/blog-bitix/2018/04/la-sentencia-try-with-resources-de-java/

2020-12-04 16:23 UTC, iuresti reviewed
Si lo que tienen en este PR ya está incluido en el otro que está aprobado, cancelen este PR porfas

2020-12-07 19:55 UTC, Nahum-png commented on Records.java
> +            String nameRecords ="C:\\Users\\Sacrificio Music\\Documents\\GRee\\Proyectofinal\\SpongeBobRace";
Esto se corrigio en el nuevo brach Crear_Clase_Record

2020-12-07 19:55 UTC, Nahum-png commented on Records.java
> +        try
Esto se corrigio en el nuevo brach Crear_Clase_Record

2020-12-07 20:02 UTC, closed without merging