Help exit buttons
Nahum-png/SpongeBob-UnderwaterAdventures pull request #6
Opened 2020-12-03 14:54 UTC by Nahum-png

2020-12-03 14:59 UTC, iuresti requested changes

2020-12-03 14:59 UTC, iuresti commented on Back.java
> +           Greenfoot.setWorld(start);
Utiliza auto-layout

2020-12-03 14:59 UTC, iuresti commented on ExitButton.java
> +         if(Greenfoot.mouseClicked(this))
Auto formatea

2020-12-04 16:22 UTC, iuresti approved these changes

2020-12-06 05:40 UTC, Alain99-hub approved these changes

2020-12-06 05:40 UTC, merged